services:
    mdkyb.website.twig.format_static_content_extension:
        class: Mdkyb\WebsiteBundle\Service\FormatStaticContentExtension
        arguments: [@router]
        tags:
            - { name: twig.extension }

    mdkyb.website.lifecycle_listener:
        class: Mdkyb\WebsiteBundle\EventListener\LifecycleListener
        arguments: [@service_container]
        tags:
            - { name: doctrine.event_listener, event: prePersist }