security:
    encoders:
        Mdkyb\WebsiteBundle\Entity\Member:
            algorithm: sha1
            encode_as_base64: true
            iterations: 22

    role_hierarchy:
        ROLE_WEB:         [ROLE_MEMBER, ROLE_SHOW_ADMIN]
        ROLE_ADMIN:       [ROLE_MEMBER, ROLE_WEB]

    providers:
        members:
            entity: 
                class: MdkybWebsiteBundle:Member
                property: email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured:
            pattern: ^/
            form_login:
                check_path: /login_check
                login_path: /login
            logout:
                path: /logout
                target: /
            anonymous: ~
            remember_me:
                key: hsdfn98n23
                lifetime: 604800
                path: /

    access_decision_manager:
        strategy: unanimous

    access_control:
        - { path: ^/admin, roles: [ROLE_SHOW_ADMIN, IS_AUTHENTICATED_FULLY] }
