security:
    encoders:
        Mdkyb\WebsiteBundle\Entity\Member:
            algorithm: sha1
            encode_as_base64: true
            iterations: 22

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        members:
            entity: 
                class: MdkybWebsiteBundle:Member
                property: email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured:
            pattern: ^/
            form_login:
                check_path: /login_check
                login_path: /login
            logout:
                path: /logout
                target: /
            anonymous: ~

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
