<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120407132024 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE BlogPost DROP FOREIGN KEY FK_4BC0361585B3E987");
        $this->addSql("DROP INDEX IDX_4BC0361585B3E987 ON BlogPost");
        $this->addSql("ALTER TABLE BlogPost DROP member_email");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE BlogPost ADD member_email VARCHAR(100) DEFAULT NULL");
        $this->addSql("ALTER TABLE BlogPost ADD CONSTRAINT FK_4BC0361585B3E987 FOREIGN KEY (member_email) REFERENCES Member(email)");
        $this->addSql("CREATE INDEX IDX_4BC0361585B3E987 ON BlogPost (member_email)");
    }
}
