<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120403232040 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE BlogPost (id INT AUTO_INCREMENT NOT NULL, member_email VARCHAR(100) DEFAULT NULL, title VARCHAR(250) NOT NULL, content VARCHAR(255) NOT NULL, publishedAt DATETIME NOT NULL, createdAt DATETIME NOT NULL, INDEX IDX_4BC0361585B3E987 (member_email), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE BlogPost ADD CONSTRAINT FK_4BC0361585B3E987 FOREIGN KEY (member_email) REFERENCES Member(email)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE BlogPost");
    }
}
